name: Android CI and Release

on:
  push:
    branches: [main, master]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fix build.gradle files
        run: |
          # Fix root build.gradle
          cat > build.gradle << 'EOL'
          // Top-level build file where you can add configuration options common to all sub-projects/modules.
          plugins {
              alias(libs.plugins.android.application) apply false
          }
          EOL

          # Fix app build.gradle to use compatible AGP version
          if [ -f "app/build.gradle" ]; then
            # Modify version in libs.versions.toml
            sed -i 's/agp = "8.9.0"/agp = "8.0.2"/g' gradle/libs.versions.toml
          fi

          # Ensure nextwebview module build.gradle is properly configured
          if [ -f "nextwebview/build.gradle" ]; then
            # Backup original file
            cp nextwebview/build.gradle nextwebview/build.gradle.bak
            
            # Update build.gradle to ensure proper publication configuration
            cat > nextwebview/build.gradle << 'EOL'
          plugins {
              id 'com.android.library'
              id 'maven-publish'
          }

          android {
              namespace 'com.levelpixel.nextwebview'
              compileSdk 35

              defaultConfig {
                  minSdk 26
                  targetSdk 35
              }

              buildFeatures {
                  buildConfig = true
              }

              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }

              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_1_8
                  targetCompatibility JavaVersion.VERSION_1_8
              }
              
              publishing {
                  singleVariant('release') {
                      withSourcesJar()
                      withJavadocJar()
                  }
              }
          }

          afterEvaluate {
              publishing {
                  publications {
                      release(MavenPublication) {
                          from components.release
                          
                          groupId = 'com.github.nettanvirdev'
                          artifactId = 'nextwebview'
                          version = '1.0.0'
                      }
                  }
              }
          }

          dependencies {
              implementation 'androidx.appcompat:appcompat:1.7.0'
          }
          EOL
          fi

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Extract version from tag
        id: tag_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build Library
        run: ./gradlew :nextwebview:assembleRelease

      - name: Build Sample App
        run: ./gradlew :app:assembleDebug

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nextwebview/build/outputs/aar/nextwebview-release.aar
          draft: false
          prerelease: false
          name: nextwebview v${{ steps.tag_version.outputs.VERSION }}
          body: |
            ## nextwebview v${{ steps.tag_version.outputs.VERSION }}

            ### Integration

            #### Gradle Groovy DSL
            ```groovy
            implementation 'com.github.nettanvirdev:nextwebview:${{ steps.tag_version.outputs.VERSION }}'
            ```

            #### Gradle Kotlin DSL
            ```kotlin
            implementation("com.github.nettanvirdev:nextwebview:${{ steps.tag_version.outputs.VERSION }}")
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Sample App Release
        id: create_app_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/debug/*.apk
          draft: false
          prerelease: false
          name: nextwebview Demo App v${{ steps.tag_version.outputs.VERSION }}
          body: |
            ## nextwebview Demo App v${{ steps.tag_version.outputs.VERSION }}

            This is a sample application demonstrating the nextwebview library capabilities.

            ### Features in this release:
            - Ad blocking
            - Popup blocking
            - Redirect protection
            - Privacy enhancements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
